### ISSUE TITLE
Invalid clearing of stored relationships

### ISSUE THREAD

**Issue by smolafilip** [WrenSecurity/wrenidm#10]
_This issue is in `historical/release/4.5.0`, it is already fixed in `develop`._
***
There is a problem with relationship setting, where existing relationships get cleared when not asked to.

The conditions in two if-statements in the `CollectionRelationshipProvider#setRelationshipValueForResource` method are reversed, which results in clearing when the `clearExisting` flag is set to `false`. This results in relationship being deleted, which were not supposed to be deleted.

**Comment by karelmaxa** [comment]
I'm closing the issue because related pull request (https://github.com/WrenSecurity/wrenidm/pull/18) has already been closed. Historical release 4.5.0 is not been supported anymore. Issue should be fixed in master.
