### ISSUE TITLE
Configure GitHub Actions CI pipeline to publish Docker images to Docker Hub

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#102]
We should configure GitHub Actions CI pipeline to publish Docker images to our [Docker Hub](https://hub.docker.com/repository/docker/wrensecurity/wrenidm) repository.

**Comment by pavelhoral** [comment]
This issue should use JDK 11 for building the image and as a base image.

Due to Activiti when building on JDK 11 the resulting package is invalid for Java 8.
