### ISSUE TITLE
SQL integration tests

### ISSUE THREAD

**Issue by krystofNovotny** [WrenSecurity/wrenidm#115]
Currently, there are no integration tests for tableHandlers making it harder to change or add new queries.

Solution for this issue is to: 
* introduce testcontainers as `test` dependency 
* write integration test for `MappedTableHandler` and `GenericTableHandler` and make sure it passes for all supported databases

**Comment by pavelhoral** [comment]
I am in the middle of refactoring openidm-jdbc-repo module and I am playing with testcontainers right now. I guess once I have PR ready this feature request will be solved by it as well.

**Comment by pavelhoral** [comment]
Testcontainers integration testing is included in #169.
