### ISSUE TITLE
Forgerock/master in version prompt

### ISSUE THREAD

**Issue by krystofNovotny** [WrenSecurity/wrenidm#116]
After idm starts, there is still forgerock/master-2016 in stdout

```
>OpenIDM ready
>OpenIDM version "6.0.0" (revision: bf8074c) forgerock/master-2016 master
```

**Comment by pavelhoral** [comment]
I created the release with `mvn release:prepare` / `mvn release:perform`. Not sure at which point _git-commit-id-maven-plugin_ resolves it's properties and at which point maven-release-plugin actually performs SCM tagging.
