### ISSUE TITLE
Docker is sunsetting Free Team Organizations

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#151]
Docker will sunset Free Team organizations on April 14, 2023 (see https://github.com/docker/hub-feedback/issues/2314). There is an opportunity to apply for the [Docker Sponsored Open Source](https://www.docker.com/community/open-source/application) program, but we may not be eligible.

We should definitely discuss migrating our [Docker images](https://hub.docker.com/r/wrensecurity/wrenidm) to another registry (_GHCR_, _GCR_, _ECR_, ...).

**Comment by pavelhoral** [comment]
FYI I have applied fot the Docker OSS program. However that does not mean we shouldn't investigate other possibilities.

> Thank you for completing the Docker Open Source application. We do our best to process applications within 30 days. We’re currently experiencing a high volume of requests and may take longer than normal to respond.

**Comment by minnoroth** [comment]
These three alternatives I listed below are in my opinion the best. All of them have OCI and Docker support and therefore allow you to use Docker CLI Commands. Also can be easily accessed from any Docker environment.

The alternatives for Docker hub are the following:
- [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
    - Free for public repositories
    - Included in GitHub Packages
- [JFrog Container Registry](https://jfrog.com/container-registry/)
    - Offers variety of features including helm repository, etc.
    - Only paid subscription (The Frog Container Registry is FREE to use for both on-premise / self-managed and SaaS in the cloud. The Cloud version includes 2GB of peak data storage, 10GB of monthly data transfer, OSS vulnerability scanning with JFrog Xray, and 2,000 monthly build minutes for JFrog Pipelines. - [link](https://jfrog.com/solution-sheet/jfrog-container-registry/#:~:text=The%20JFrog%20Container%20Registry%20is%20FREE%20to%20use%20for%20both%20on%2Dpremise%20/%20self%2Dmanaged%20and%20SaaS%20in%20the%20cloud.%20The%20Cloud%20version%20includes%202GB%20of%20peak%20data%20storage%2C%2010GB%20of%20monthly%20data%20transfer%2C%20OSS%20vulnerability%20scanning%20with%20JFrog%20Xray%2C%20and%202%2C000%20monthly%20build%20minutes%20for%20JFrog%20Pipelines.))
- [Amazon Elastic Container Registry](https://aws.amazon.com/ecr/)
    - Almost free for public projects (You pay only for Data Transfers OUT, that are greater than 5 TB / month to non AWS Regions. - [link](https://aws.amazon.com/ecr/pricing/#:~:text=Greater%20than%205%20TB%20/%20month%20to%20non%20AWS%20Regions))
    - AWS Account needed

Other honorable mentions:
- [GitLab Container Registry](https://docs.gitlab.com/ee/user/packages/container_registry/)
- [Google Container Registry](https://cloud.google.com/container-registry)

Considering the fact that Wren Security already has its public repositories based on GitHub I feel like GitHub Container Registry would be the best option. The images itself can be associated with a repository so the linking between these two would make sense as well. The whole Wren Security suite being open-source also helps as GitHub offers GitHub Packages completely free of charge to all public repositories.

**Comment by pavelhoral** [comment]
> On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan.
> 
> If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased.
> 
> We apologize for the alarm our decision caused. For more details, please [visit our FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKtH6Gq4qF0xTWP46LMF_OtKgQBAhMK58inFdlIek_VRMEoUAPEwsCOixXrILBepbtqbKh-9Q=).

**Comment by pavelhoral** [comment]
We are part of DockerHub's OSS program. We can close this issue. We can reconsider deploying images to multiple registries if requested by users in the future.
