### ISSUE TITLE
Remove BoneCP from openidm-repo-jdbc

### ISSUE THREAD

**Issue by pavelhoral** [WrenSecurity/wrenidm#166]
Module openidm-repo-jdbc contains BoneCP components. BoneCP project has been sunsetted in favor of HikariCP. We should investigate what is the current state of things in Wren:IDM codebase and if it is possible to remove BoneCP components completely or if there is a reason why we still have it there.

**Comment by karelmaxa** [comment]
Resolved in https://github.com/WrenSecurity/wrenidm/pull/179.
