### ISSUE TITLE
Support "_totalPagedResultsPolicy" parameter when calling openidm.query

### ISSUE THREAD

**Issue by krausvo1** [WrenSecurity/wrenidm#188]
Parameters for `openidm.query` cannot contain `_totalPagedResultsPolicy` parameter at the moment. If the parameter is included, following error appears:

```
{"code":400,"reason":"Bad Request","message":"Unrecognized request parameter '_totalPagedResultsPolicy'","detail":{}}
```

This parameter is necessary to support query requests with paging. Query request done via REST API supports this parameter already, e.g. `GET /managed/user?_queryFilter=true&_totalPagedResultsPolicy=EXACT&_pageSize=10&_pagedResultsOffset=0`.

**Comment by krausvo1** [comment]
The parameter probably needs to be added to [ResourceFunctions#query](https://github.com/WrenSecurity/wrenidm/blob/main/openidm-script/src/main/java/org/forgerock/openidm/script/ResourceFunctions.java#L673) method.

**Comment by pavelhoral** [comment]
Fixed by https://github.com/WrenSecurity/wrenidm/pull/189
