### ISSUE TITLE
Update README + add contributor instructions

### ISSUE THREAD

**Issue by GuyPaddock** [WrenSecurity/wrenidm#28]
Our team is starting to get into Wren's copies of OpenIDM (Wren:IDM I guess?) but we noticed the README for the project still refers to ForgeRock's site + repositories. Might be a good idea to update that and provide some details about how to contribute.

**Comment by siepkes** [comment]
Definitely a good idea. I did something similar for the [Wren:AM](https://github.com/WrenSecurity/wrenam) 13.5 branch.

**Comment by pavelhoral** [comment]
README was updated in 4e5e7db9. Closing as resolved (no need for backport IMO).
