### ISSUE TITLE
Update POMs for Wren:IDM 4.0 to build from Wren JFrog

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrenidm#29]
the title says it all -- we need to update the POMs to:
- create a `sustaining/4.0` branch.
- archive all older FR branches as tags.
- no longer ping FR Maven.
- use `wrensecurity.jfrog.io` to resolve the wrensec parent POM (still called `forgerock-parent` for now).
- build properly under JDK 8 (usually involves fixing Javadocs).
- rename modules / artifacts to use "Wren:XYZ" naming so it's easy for users to tell artifacts we produce apart from those produced by FR in case a user ends up with a mixed set.

**Comment by karelmaxa** [comment]
I'm closing this issue because we are supporting only release Wren:IDM 6 that is fully buildable with our JFrog repository.
