### ISSUE TITLE
NPE in getting execution listener from deleted process instance

### ISSUE THREAD

**Issue by smolafilip** [WrenSecurity/wrenidm#3]
NullPointerException is thrown when getting the activity when calling the end execution process listener during the DELETE process instance action.

The NPE is caused by the lines:
```((ExecutionEntity) variableScope).getActivity().getActivityBehavior();```
and
```((ExecutionEntity) variableScope).getActivity().getExecutionListeners(eventName);```
in the `OpenIDMResolverFactory#createResolver` method.

A solution could be first checking whether `getActivity()` returns `null` and handling that case separately.

**Comment by karelmaxa** [comment]
Related pull request has been merged.
