### ISSUE TITLE
Create a new Wren:IDM `getting-started` sample

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrenidm#32]
For licensing reasons, the `getting-started.bat` and `getting-started.sh` scripts, along with the samples they referenced, are being removed in https://github.com/WrenSecurity/wrenidm/pull/21. This seriously hinders the ability of new Wren:IDM users to try out our fork, and puts us at a disadvantage compared to FR.

We should create a new getting started sample.

**Comment by karelmaxa** [comment]
We have created [wrenidm-cookbook](https://github.com/WrenSecurity/wrenidm-cookbook) with recipes (samples) demonstrating key Wren:IDM features. I think that we don't need dedicated `getting-started` scripts in this moment.
