### ISSUE TITLE
[5.5.0] Multiple test failures (openidm-provisioner-openicf + openidm-security)

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrenidm#37]
## Affected Versions
- 5.5.0 (`feature/wrensec-builds-phase-3`, at ff791d05418eb353254c4449d3ae8c2e4aa2bee7)

## Summary
Multiple tests are failing when the project is compiled.

## Repro Steps
1. Clone the [`wrenidm`](https://github.com/WrenSecurity/wrenidm) repository to the local machine, checked out at ff791d05418eb353254c4449d3ae8c2e4aa2bee7.
2. Build the project with `mvn clean install -Dignore-artifact-sigs` (signatures need to be skipped to avoid https://github.com/s4u/pgpverify-maven-plugin/issues/29).

## Desired
- All tests pass.
- The build completes successfully.

## Actual
- 20 out of 113 tests fail in the `OpenICFProvisionerServiceTest`. The error message is "Not Found" for all tests -- possibly an endpoint has changed locations or request routing is broken/misconfigured?
- 18 out of 18 tests fail in the `PrivateKeyResourceProviderTest`. The error is always an NPE in `SecurityTestUtils.createKeyStore(SecurityTestUtils.java:49)`.

See attached logs.
[Test failures in 5.5-SNAPSHOT.txt](https://github.com/WrenSecurity/wrenidm/files/1801306/Test.failures.in.5.5-SNAPSHOT.txt)

**Comment by karelmaxa** [comment]
Issue has been probably fixed in PR https://github.com/WrenSecurity/wrenidm/pull/55. Current build of main development branch is passing all existing tests.
