### ISSUE TITLE
[5.5.0] Cannot use "integer" field types

### ISSUE THREAD

**Issue by GuyPaddock** [WrenSecurity/wrenidm#41]
## Affected Versions
- 5.5.0 (`master`, at 731844f)

## Summary
If a managed object field type is changed to "integer", managed objects cannot be saved if they contain that field because the field will never validate.

## Steps to Reproduce
1. Start OpenIDM with default project
2. Navigate to https://localhost:8443/admin/#managed/edit/user/
3. Click the "Schema" tab.
4. Add a new "XRef ID" field that is of type "integer" and viewable. 
5. Save the schema.
6. Attempt to add a new user, providing an integer value for the new "XRef ID" field (e.g. the value `10`).

## Expected Results
The new user is saved properly.

## Actual Results
- The following error appears:
```
Unable to update resource. Validation Failed.
Reason(s):
- xRefId: common.form.validation.VALID_TYPE
```
- The model is not saved.
- See attached (partially redacted) HAR.
[dev-idm.validation_failed.har](https://github.com/WrenSecurity/wrenidm/files/1813901/dev-idm.validation_failed.har.txt)

**Comment by karelmaxa** [comment]
Fixed through https://github.com/WrenSecurity/wrenidm/pull/68.
