### ISSUE TITLE
Update wrensec-commons to 22.0.0

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#69]
_Wrensec-commons_ dependency should be updated from current alpha version (_21.0.0-alpha-23_) to our latest release (_22.0.0_).

**Comment by siepkes** [comment]
@karelmaxa There will be a release made of `wrensec-commons` pretty soon (ie. `22.0.0`) by @Kortanul.

**Comment by karelmaxa** [comment]
@siepkes OK, thanks for info. I will update it immediately after release. 

There are some runtime issues so i have to fix them first.

**Comment by siepkes** [comment]
@karelmaxa If you find any issues with `wrensec-commons` itself give us a ping so we can incorporate them in the upcomming release.
