### ISSUE TITLE
Configure GitHub Actions CI pipeline

### ISSUE THREAD

**Issue by karelmaxa** [WrenSecurity/wrenidm#74]
It would be nice to replace current `SemaphoreCI` integration with the `GitHub Actions` CI pipeline.

I am proposing to switch to GitHub Actions for several reasons:

* Pipelines are configured through _YAML_ files in git repository
* Current pipelines are not stable (see strange error in https://github.com/WrenSecurity/wrensec-commons/pull/23)
* By using GitHub Actions we will have everything under one roof
* **TBD**

**Comment by pavelhoral** [comment]
Another feature that might be easier to achieve within GH Actions is drafting releases.

**Comment by karelmaxa** [comment]
Base `Github Action` pipeline performing maven verify phase has been configured.
