### ISSUE TITLE
Unable to build openidm-ui on macOS due to 32-bit PhantomJS

### ISSUE THREAD

**Issue by RoBobik** [WrenSecurity/wrenidm#96]
## Summary

Module `openidm-ui-admin` cannot be built on macOS >= 10.15 (Catalina) because `"grunt-contrib-qunit": "0.4.0"` uses unsupported 32-bit binary of PhantomJS.

## Steps

1. Clone master (f7236ce15)
2. Run `mvn clean package`

## Current behavior

Build fails with the following error:
```
[INFO] --- frontend-maven-plugin:0.0.28:grunt (grunt) @ openidm-ui-admin ---
[...]
[INFO] Running 'grunt build:dev --target-version=6.0.0-SNAPSHOT' in /Users/Documents/WorkMode/wren/project-dragon/wrenidm/openidm-ui/openidm-ui-admin
[...]
[INFO] Running "qunit:test" (qunit) task
[INFO] Testing target/qunit/index.html Warning: spawn Unknown system error -86 Use --force to continue.
[INFO]
[INFO] Aborted due to warnings.
```

## Expected behavior

Build is finished without error.

## Environment

```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.3
BuildVersion:   20E232
```

## Details

I tried to build `openidm-ui-admin` manually via NPM with a consistent result:
```
$ cd wrenidm/openidm-ui/openidm-ui-admin
$ npm i
$ node_modules/.bin/grunt build:dev
[...]
Running "qunit:test" (qunit) task
Testing target/qunit/index.html Warning: spawn Unknown system error -86 Use --force to continue.

Aborted due to warnings.
```

After trying to run it with latest `grunt-contrib-qunit` (3.0.0, then 4.0.0) which no longer uses PhantomJS, I suspected the problem is caused by PhantomJS binary.

Running and inspecting the PhantomJS binary reveals that it's a 32-bit application:
```
$ ./node_modules/phantomjs/lib/phantom/bin/phantomjs
zsh: bad CPU type in executable: ./node_modules/phantomjs/lib/phantom/bin/phantomjs

$ file ./node_modules/phantomjs/lib/phantom/bin/phantomjs
./node_modules/phantomjs/lib/phantom/bin/phantomjs: Mach-O executable i386
```

Support for 32-bit application has been removed from macOS since Catalina (10.15).

## Possible solution

Upgrade `grunt-contrib-qunit` to latest version (`4.0.0`). It uses Puppeteer instead of PhantomJS since 3.0.0, so additional configuration will have to be made in order for tests to work (allow CORS, fix path to target html, ...).

*It will require newer NodeJS as well.* I was able to run it on latest Node but the project uses ancient Node 4.4.2.

Simply using latest (4 years old and **deprecated**) 64-bit version of PhantomJS `"phantomjs-prebuilt": "2.1.16"` won't work because the package has a different name, so it is not used by `qunit`.

**Comment by pavelhoral** [comment]
We need to start fixing this in https://github.com/WrenSecurity/wrensec-ui which suffers with the same issue.
